const appointmentsClinic1 = [
  {
    AppointmentID: 115,
    AppointmentDatetime: '2026-03-09T15:00:00.000Z',
    AppointmentPatientID: 37,
    AppointmentClinicID: 1,
    AppointmentStaffID: 4,
    AppointmentStatusID: 1,
    AppointmentPatientFirstname: 'Mariam',
    AppointmentPatientLastname: 'AlFarsi',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Jack',
    AppointmentStaffLastname: 'Turner',
    AppointmentStatusName: 'Pending',
  },
  {
    AppointmentID: 106,
    AppointmentDatetime: '2026-02-25T17:00:00.000Z',
    AppointmentPatientID: 41,
    AppointmentClinicID: 1,
    AppointmentStaffID: 2,
    AppointmentStatusID: 1,
    AppointmentPatientFirstname: 'Imran',
    AppointmentPatientLastname: 'Siddiqui',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Farhan',
    AppointmentStaffLastname: 'Ali',
    AppointmentStatusName: 'Pending',
  },
  {
    AppointmentID: 81,
    AppointmentDatetime: '2026-02-02T11:00:00.000Z',
    AppointmentPatientID: 6,
    AppointmentClinicID: 1,
    AppointmentStaffID: 2,
    AppointmentStatusID: 2,
    AppointmentPatientFirstname: 'Leila',
    AppointmentPatientLastname: 'Haddad',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Farhan',
    AppointmentStaffLastname: 'Ali',
    AppointmentStatusName: 'Delivered',
  },
  {
    AppointmentID: 74,
    AppointmentDatetime: '2026-01-26T14:00:00.000Z',
    AppointmentPatientID: 37,
    AppointmentClinicID: 1,
    AppointmentStaffID: 4,
    AppointmentStatusID: 3,
    AppointmentPatientFirstname: 'Mariam',
    AppointmentPatientLastname: 'AlFarsi',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Jack',
    AppointmentStaffLastname: 'Turner',
    AppointmentStatusName: 'No show',
  },
  {
    AppointmentID: 58,
    AppointmentDatetime: '2026-01-11T14:00:00.000Z',
    AppointmentPatientID: 89,
    AppointmentClinicID: 1,
    AppointmentStaffID: 4,
    AppointmentStatusID: 2,
    AppointmentPatientFirstname: 'Sara',
    AppointmentPatientLastname: 'Ahmadi',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Jack',
    AppointmentStaffLastname: 'Turner',
    AppointmentStatusName: 'Delivered',
  },
  {
    AppointmentID: 60,
    AppointmentDatetime: '2026-01-11T09:00:00.000Z',
    AppointmentPatientID: 54,
    AppointmentClinicID: 1,
    AppointmentStaffID: 2,
    AppointmentStatusID: 4,
    AppointmentPatientFirstname: 'Alina',
    AppointmentPatientLastname: 'Popescu',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Farhan',
    AppointmentStaffLastname: 'Ali',
    AppointmentStatusName: 'No delivery',
  },
  {
    AppointmentID: 56,
    AppointmentDatetime: '2026-01-09T17:00:00.000Z',
    AppointmentPatientID: 31,
    AppointmentClinicID: 1,
    AppointmentStaffID: 4,
    AppointmentStatusID: 2,
    AppointmentPatientFirstname: 'Hannah',
    AppointmentPatientLastname: 'Wright',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Jack',
    AppointmentStaffLastname: 'Turner',
    AppointmentStatusName: 'Delivered',
  },
  {
    AppointmentID: 52,
    AppointmentDatetime: '2026-01-03T17:00:00.000Z',
    AppointmentPatientID: 56,
    AppointmentClinicID: 1,
    AppointmentStaffID: 4,
    AppointmentStatusID: 2,
    AppointmentPatientFirstname: 'Mehdi',
    AppointmentPatientLastname: 'Farouk',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Jack',
    AppointmentStaffLastname: 'Turner',
    AppointmentStatusName: 'Delivered',
  },
  {
    AppointmentID: 42,
    AppointmentDatetime: '2025-12-26T17:00:00.000Z',
    AppointmentPatientID: 95,
    AppointmentClinicID: 1,
    AppointmentStaffID: 2,
    AppointmentStatusID: 2,
    AppointmentPatientFirstname: 'Yusuf',
    AppointmentPatientLastname: 'Aziz',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Farhan',
    AppointmentStaffLastname: 'Ali',
    AppointmentStatusName: 'Delivered',
  },
  {
    AppointmentID: 37,
    AppointmentDatetime: '2025-12-20T16:00:00.000Z',
    AppointmentPatientID: 98,
    AppointmentClinicID: 1,
    AppointmentStaffID: 4,
    AppointmentStatusID: 2,
    AppointmentPatientFirstname: 'Amal',
    AppointmentPatientLastname: 'Saad',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Jack',
    AppointmentStaffLastname: 'Turner',
    AppointmentStatusName: 'Delivered',
  },
  {
    AppointmentID: 29,
    AppointmentDatetime: '2025-12-12T12:00:00.000Z',
    AppointmentPatientID: 44,
    AppointmentClinicID: 1,
    AppointmentStaffID: 4,
    AppointmentStatusID: 2,
    AppointmentPatientFirstname: 'Abdul',
    AppointmentPatientLastname: 'Rahman',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Jack',
    AppointmentStaffLastname: 'Turner',
    AppointmentStatusName: 'Delivered',
  },
  {
    AppointmentID: 28,
    AppointmentDatetime: '2025-12-09T16:00:00.000Z',
    AppointmentPatientID: 7,
    AppointmentClinicID: 1,
    AppointmentStaffID: 2,
    AppointmentStatusID: 2,
    AppointmentPatientFirstname: 'Thomas',
    AppointmentPatientLastname: 'Hughes',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Farhan',
    AppointmentStaffLastname: 'Ali',
    AppointmentStatusName: 'Delivered',
  },
  {
    AppointmentID: 27,
    AppointmentDatetime: '2025-12-08T16:00:00.000Z',
    AppointmentPatientID: 2,
    AppointmentClinicID: 1,
    AppointmentStaffID: 4,
    AppointmentStatusID: 2,
    AppointmentPatientFirstname: 'Priya',
    AppointmentPatientLastname: 'Patel',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Jack',
    AppointmentStaffLastname: 'Turner',
    AppointmentStatusName: 'Delivered',
  },
  {
    AppointmentID: 17,
    AppointmentDatetime: '2025-11-30T09:00:00.000Z',
    AppointmentPatientID: 74,
    AppointmentClinicID: 1,
    AppointmentStaffID: 2,
    AppointmentStatusID: 2,
    AppointmentPatientFirstname: 'Owen',
    AppointmentPatientLastname: 'Scott',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Farhan',
    AppointmentStaffLastname: 'Ali',
    AppointmentStatusName: 'Delivered',
  },
  {
    AppointmentID: 12,
    AppointmentDatetime: '2025-11-24T16:00:00.000Z',
    AppointmentPatientID: 88,
    AppointmentClinicID: 1,
    AppointmentStaffID: 4,
    AppointmentStatusID: 2,
    AppointmentPatientFirstname: 'Noah',
    AppointmentPatientLastname: 'Harris',
    AppointmentClinicName: 'TravelJabs Brighton',
    AppointmentStaffFirstname: 'Jack',
    AppointmentStaffLastname: 'Turner',
    AppointmentStatusName: 'Delivered',
  },
];
