const vaccinations = [
  {
    VaccinationID: 1,
    VaccinationAppointmentID: 1,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 2,
    VaccinationAppointmentID: 2,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 3,
    VaccinationAppointmentID: 3,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 4,
    VaccinationAppointmentID: 3,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 5,
    VaccinationAppointmentID: 3,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 6,
    VaccinationAppointmentID: 3,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 7,
    VaccinationAppointmentID: 3,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 8,
    VaccinationAppointmentID: 4,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 9,
    VaccinationAppointmentID: 4,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 10,
    VaccinationAppointmentID: 5,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 11,
    VaccinationAppointmentID: 5,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 12,
    VaccinationAppointmentID: 5,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 13,
    VaccinationAppointmentID: 5,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 14,
    VaccinationAppointmentID: 5,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 15,
    VaccinationAppointmentID: 6,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 16,
    VaccinationAppointmentID: 7,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 17,
    VaccinationAppointmentID: 7,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 18,
    VaccinationAppointmentID: 8,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 19,
    VaccinationAppointmentID: 8,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 20,
    VaccinationAppointmentID: 8,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 21,
    VaccinationAppointmentID: 9,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 22,
    VaccinationAppointmentID: 9,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 23,
    VaccinationAppointmentID: 10,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 24,
    VaccinationAppointmentID: 10,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 25,
    VaccinationAppointmentID: 10,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 26,
    VaccinationAppointmentID: 11,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 27,
    VaccinationAppointmentID: 11,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 28,
    VaccinationAppointmentID: 11,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 29,
    VaccinationAppointmentID: 11,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 30,
    VaccinationAppointmentID: 11,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 31,
    VaccinationAppointmentID: 12,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 32,
    VaccinationAppointmentID: 13,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 33,
    VaccinationAppointmentID: 13,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 34,
    VaccinationAppointmentID: 14,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 35,
    VaccinationAppointmentID: 15,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 36,
    VaccinationAppointmentID: 15,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 37,
    VaccinationAppointmentID: 16,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 38,
    VaccinationAppointmentID: 16,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 39,
    VaccinationAppointmentID: 16,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 40,
    VaccinationAppointmentID: 16,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 41,
    VaccinationAppointmentID: 16,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 42,
    VaccinationAppointmentID: 16,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 43,
    VaccinationAppointmentID: 17,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 44,
    VaccinationAppointmentID: 17,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 45,
    VaccinationAppointmentID: 18,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 46,
    VaccinationAppointmentID: 18,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 47,
    VaccinationAppointmentID: 18,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 48,
    VaccinationAppointmentID: 19,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 49,
    VaccinationAppointmentID: 19,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 50,
    VaccinationAppointmentID: 20,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 51,
    VaccinationAppointmentID: 20,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 52,
    VaccinationAppointmentID: 20,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 53,
    VaccinationAppointmentID: 21,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 54,
    VaccinationAppointmentID: 21,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 55,
    VaccinationAppointmentID: 22,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 56,
    VaccinationAppointmentID: 22,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 57,
    VaccinationAppointmentID: 22,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 58,
    VaccinationAppointmentID: 22,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 59,
    VaccinationAppointmentID: 23,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 60,
    VaccinationAppointmentID: 23,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 61,
    VaccinationAppointmentID: 23,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 62,
    VaccinationAppointmentID: 24,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 63,
    VaccinationAppointmentID: 24,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 64,
    VaccinationAppointmentID: 24,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 65,
    VaccinationAppointmentID: 25,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 66,
    VaccinationAppointmentID: 26,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 67,
    VaccinationAppointmentID: 26,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 68,
    VaccinationAppointmentID: 26,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 69,
    VaccinationAppointmentID: 26,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 70,
    VaccinationAppointmentID: 27,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 71,
    VaccinationAppointmentID: 28,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 72,
    VaccinationAppointmentID: 28,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 73,
    VaccinationAppointmentID: 29,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 74,
    VaccinationAppointmentID: 29,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 75,
    VaccinationAppointmentID: 29,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 76,
    VaccinationAppointmentID: 29,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 77,
    VaccinationAppointmentID: 30,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 78,
    VaccinationAppointmentID: 31,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 79,
    VaccinationAppointmentID: 31,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 80,
    VaccinationAppointmentID: 31,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 81,
    VaccinationAppointmentID: 31,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 82,
    VaccinationAppointmentID: 31,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 83,
    VaccinationAppointmentID: 32,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 84,
    VaccinationAppointmentID: 33,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 85,
    VaccinationAppointmentID: 34,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 86,
    VaccinationAppointmentID: 34,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 87,
    VaccinationAppointmentID: 34,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 88,
    VaccinationAppointmentID: 35,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 89,
    VaccinationAppointmentID: 36,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 90,
    VaccinationAppointmentID: 36,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 91,
    VaccinationAppointmentID: 36,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 92,
    VaccinationAppointmentID: 36,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 93,
    VaccinationAppointmentID: 37,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 94,
    VaccinationAppointmentID: 37,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 95,
    VaccinationAppointmentID: 37,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 96,
    VaccinationAppointmentID: 38,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 97,
    VaccinationAppointmentID: 39,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 98,
    VaccinationAppointmentID: 39,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 99,
    VaccinationAppointmentID: 39,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 100,
    VaccinationAppointmentID: 40,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 101,
    VaccinationAppointmentID: 41,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 102,
    VaccinationAppointmentID: 41,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 103,
    VaccinationAppointmentID: 41,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 104,
    VaccinationAppointmentID: 42,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 105,
    VaccinationAppointmentID: 42,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 106,
    VaccinationAppointmentID: 42,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 107,
    VaccinationAppointmentID: 42,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 108,
    VaccinationAppointmentID: 42,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 109,
    VaccinationAppointmentID: 43,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 110,
    VaccinationAppointmentID: 43,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 111,
    VaccinationAppointmentID: 43,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 112,
    VaccinationAppointmentID: 43,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 113,
    VaccinationAppointmentID: 44,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 114,
    VaccinationAppointmentID: 44,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 115,
    VaccinationAppointmentID: 45,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 116,
    VaccinationAppointmentID: 45,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 117,
    VaccinationAppointmentID: 46,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 118,
    VaccinationAppointmentID: 46,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 119,
    VaccinationAppointmentID: 47,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 120,
    VaccinationAppointmentID: 48,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 121,
    VaccinationAppointmentID: 49,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 122,
    VaccinationAppointmentID: 50,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 123,
    VaccinationAppointmentID: 50,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 124,
    VaccinationAppointmentID: 50,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 125,
    VaccinationAppointmentID: 50,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 126,
    VaccinationAppointmentID: 50,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 127,
    VaccinationAppointmentID: 51,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 128,
    VaccinationAppointmentID: 52,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 129,
    VaccinationAppointmentID: 52,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 130,
    VaccinationAppointmentID: 53,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 131,
    VaccinationAppointmentID: 54,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 132,
    VaccinationAppointmentID: 54,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 133,
    VaccinationAppointmentID: 54,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 134,
    VaccinationAppointmentID: 54,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 135,
    VaccinationAppointmentID: 55,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 136,
    VaccinationAppointmentID: 55,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 137,
    VaccinationAppointmentID: 55,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 138,
    VaccinationAppointmentID: 55,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 139,
    VaccinationAppointmentID: 55,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 140,
    VaccinationAppointmentID: 56,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 141,
    VaccinationAppointmentID: 57,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 142,
    VaccinationAppointmentID: 58,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 143,
    VaccinationAppointmentID: 59,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 144,
    VaccinationAppointmentID: 59,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 145,
    VaccinationAppointmentID: 59,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 146,
    VaccinationAppointmentID: 60,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 147,
    VaccinationAppointmentID: 60,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 148,
    VaccinationAppointmentID: 60,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 149,
    VaccinationAppointmentID: 61,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 150,
    VaccinationAppointmentID: 61,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 151,
    VaccinationAppointmentID: 61,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 152,
    VaccinationAppointmentID: 61,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 153,
    VaccinationAppointmentID: 61,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 154,
    VaccinationAppointmentID: 62,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 155,
    VaccinationAppointmentID: 62,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 156,
    VaccinationAppointmentID: 62,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 157,
    VaccinationAppointmentID: 63,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 158,
    VaccinationAppointmentID: 63,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 159,
    VaccinationAppointmentID: 63,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 160,
    VaccinationAppointmentID: 64,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 161,
    VaccinationAppointmentID: 64,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 162,
    VaccinationAppointmentID: 64,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 163,
    VaccinationAppointmentID: 64,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 164,
    VaccinationAppointmentID: 65,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 165,
    VaccinationAppointmentID: 65,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 166,
    VaccinationAppointmentID: 66,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 167,
    VaccinationAppointmentID: 66,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 168,
    VaccinationAppointmentID: 66,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 169,
    VaccinationAppointmentID: 66,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 170,
    VaccinationAppointmentID: 67,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 171,
    VaccinationAppointmentID: 67,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 172,
    VaccinationAppointmentID: 67,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 173,
    VaccinationAppointmentID: 68,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 174,
    VaccinationAppointmentID: 69,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 175,
    VaccinationAppointmentID: 69,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 176,
    VaccinationAppointmentID: 70,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 177,
    VaccinationAppointmentID: 70,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 178,
    VaccinationAppointmentID: 70,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 179,
    VaccinationAppointmentID: 70,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 180,
    VaccinationAppointmentID: 70,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 181,
    VaccinationAppointmentID: 71,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 182,
    VaccinationAppointmentID: 71,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 183,
    VaccinationAppointmentID: 72,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 184,
    VaccinationAppointmentID: 72,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 185,
    VaccinationAppointmentID: 72,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 186,
    VaccinationAppointmentID: 73,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 187,
    VaccinationAppointmentID: 73,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 188,
    VaccinationAppointmentID: 73,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 189,
    VaccinationAppointmentID: 73,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 190,
    VaccinationAppointmentID: 73,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 191,
    VaccinationAppointmentID: 74,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 192,
    VaccinationAppointmentID: 74,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 193,
    VaccinationAppointmentID: 74,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 194,
    VaccinationAppointmentID: 74,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 195,
    VaccinationAppointmentID: 74,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 196,
    VaccinationAppointmentID: 75,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 197,
    VaccinationAppointmentID: 75,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 198,
    VaccinationAppointmentID: 75,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 199,
    VaccinationAppointmentID: 75,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 200,
    VaccinationAppointmentID: 75,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 201,
    VaccinationAppointmentID: 75,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 202,
    VaccinationAppointmentID: 76,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 203,
    VaccinationAppointmentID: 77,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 204,
    VaccinationAppointmentID: 77,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 205,
    VaccinationAppointmentID: 77,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 206,
    VaccinationAppointmentID: 77,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 207,
    VaccinationAppointmentID: 77,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 208,
    VaccinationAppointmentID: 78,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 209,
    VaccinationAppointmentID: 78,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 210,
    VaccinationAppointmentID: 78,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 211,
    VaccinationAppointmentID: 78,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 212,
    VaccinationAppointmentID: 78,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 213,
    VaccinationAppointmentID: 79,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 214,
    VaccinationAppointmentID: 80,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 215,
    VaccinationAppointmentID: 80,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 216,
    VaccinationAppointmentID: 81,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 217,
    VaccinationAppointmentID: 81,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 218,
    VaccinationAppointmentID: 81,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 219,
    VaccinationAppointmentID: 81,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 220,
    VaccinationAppointmentID: 81,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 221,
    VaccinationAppointmentID: 82,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 222,
    VaccinationAppointmentID: 82,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 223,
    VaccinationAppointmentID: 83,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 224,
    VaccinationAppointmentID: 84,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 225,
    VaccinationAppointmentID: 84,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 226,
    VaccinationAppointmentID: 84,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 227,
    VaccinationAppointmentID: 84,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 228,
    VaccinationAppointmentID: 85,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 229,
    VaccinationAppointmentID: 85,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 230,
    VaccinationAppointmentID: 85,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 231,
    VaccinationAppointmentID: 86,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 232,
    VaccinationAppointmentID: 86,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 233,
    VaccinationAppointmentID: 86,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 234,
    VaccinationAppointmentID: 87,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 235,
    VaccinationAppointmentID: 87,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 236,
    VaccinationAppointmentID: 87,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 237,
    VaccinationAppointmentID: 88,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 238,
    VaccinationAppointmentID: 88,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 239,
    VaccinationAppointmentID: 89,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 240,
    VaccinationAppointmentID: 89,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 241,
    VaccinationAppointmentID: 89,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 242,
    VaccinationAppointmentID: 89,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 243,
    VaccinationAppointmentID: 89,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 244,
    VaccinationAppointmentID: 90,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 245,
    VaccinationAppointmentID: 90,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 246,
    VaccinationAppointmentID: 90,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 247,
    VaccinationAppointmentID: 90,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 248,
    VaccinationAppointmentID: 91,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 249,
    VaccinationAppointmentID: 91,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 250,
    VaccinationAppointmentID: 91,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 251,
    VaccinationAppointmentID: 91,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 252,
    VaccinationAppointmentID: 92,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 253,
    VaccinationAppointmentID: 93,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 254,
    VaccinationAppointmentID: 94,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 255,
    VaccinationAppointmentID: 94,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 256,
    VaccinationAppointmentID: 94,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 257,
    VaccinationAppointmentID: 94,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 258,
    VaccinationAppointmentID: 95,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 259,
    VaccinationAppointmentID: 95,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 260,
    VaccinationAppointmentID: 95,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 261,
    VaccinationAppointmentID: 96,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 262,
    VaccinationAppointmentID: 96,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 263,
    VaccinationAppointmentID: 96,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 264,
    VaccinationAppointmentID: 96,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 265,
    VaccinationAppointmentID: 97,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 266,
    VaccinationAppointmentID: 97,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 267,
    VaccinationAppointmentID: 97,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 268,
    VaccinationAppointmentID: 98,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 269,
    VaccinationAppointmentID: 98,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 270,
    VaccinationAppointmentID: 98,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 271,
    VaccinationAppointmentID: 99,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 272,
    VaccinationAppointmentID: 99,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 273,
    VaccinationAppointmentID: 100,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 274,
    VaccinationAppointmentID: 101,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 275,
    VaccinationAppointmentID: 101,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 276,
    VaccinationAppointmentID: 102,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 277,
    VaccinationAppointmentID: 102,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 278,
    VaccinationAppointmentID: 102,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 279,
    VaccinationAppointmentID: 103,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 280,
    VaccinationAppointmentID: 103,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 281,
    VaccinationAppointmentID: 103,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 282,
    VaccinationAppointmentID: 104,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 283,
    VaccinationAppointmentID: 104,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 284,
    VaccinationAppointmentID: 104,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 285,
    VaccinationAppointmentID: 104,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 286,
    VaccinationAppointmentID: 104,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 287,
    VaccinationAppointmentID: 105,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 288,
    VaccinationAppointmentID: 106,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 289,
    VaccinationAppointmentID: 107,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 290,
    VaccinationAppointmentID: 107,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 291,
    VaccinationAppointmentID: 107,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 292,
    VaccinationAppointmentID: 108,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 293,
    VaccinationAppointmentID: 109,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 294,
    VaccinationAppointmentID: 109,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 295,
    VaccinationAppointmentID: 109,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 296,
    VaccinationAppointmentID: 109,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 297,
    VaccinationAppointmentID: 110,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 298,
    VaccinationAppointmentID: 111,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 299,
    VaccinationAppointmentID: 111,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 300,
    VaccinationAppointmentID: 111,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 301,
    VaccinationAppointmentID: 111,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 302,
    VaccinationAppointmentID: 111,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 303,
    VaccinationAppointmentID: 112,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 304,
    VaccinationAppointmentID: 112,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
  {
    VaccinationID: 305,
    VaccinationAppointmentID: 112,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 306,
    VaccinationAppointmentID: 113,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 307,
    VaccinationAppointmentID: 114,
    VaccinationVaccineID: 6,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Influenza',
    VaccinationVaccineCost: '18.00',
  },
  {
    VaccinationID: 308,
    VaccinationAppointmentID: 114,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 309,
    VaccinationAppointmentID: 114,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 310,
    VaccinationAppointmentID: 114,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 311,
    VaccinationAppointmentID: 114,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 312,
    VaccinationAppointmentID: 115,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 313,
    VaccinationAppointmentID: 115,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 314,
    VaccinationAppointmentID: 115,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 315,
    VaccinationAppointmentID: 115,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 316,
    VaccinationAppointmentID: 115,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 317,
    VaccinationAppointmentID: 116,
    VaccinationVaccineID: 1,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Hepatitis A',
    VaccinationVaccineCost: '65.00',
  },
  {
    VaccinationID: 318,
    VaccinationAppointmentID: 116,
    VaccinationVaccineID: 5,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Rabies',
    VaccinationVaccineCost: '95.00',
  },
  {
    VaccinationID: 319,
    VaccinationAppointmentID: 116,
    VaccinationVaccineID: 9,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Yellow fever',
    VaccinationVaccineCost: '85.00',
  },
  {
    VaccinationID: 320,
    VaccinationAppointmentID: 116,
    VaccinationVaccineID: 4,
    VaccinationOutcomeID: 2,
    VaccinationVaccineName: 'Hepatitis B',
    VaccinationVaccineCost: '60.00',
  },
  {
    VaccinationID: 321,
    VaccinationAppointmentID: 117,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 322,
    VaccinationAppointmentID: 118,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 323,
    VaccinationAppointmentID: 119,
    VaccinationVaccineID: 8,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Measles / Mumps / Rubella (MMR)',
    VaccinationVaccineCost: '40.00',
  },
  {
    VaccinationID: 324,
    VaccinationAppointmentID: 119,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 325,
    VaccinationAppointmentID: 119,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 326,
    VaccinationAppointmentID: 120,
    VaccinationVaccineID: 3,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Tetanus / Diphtheria / Polio (Td/IPV booster)',
    VaccinationVaccineCost: '45.00',
  },
  {
    VaccinationID: 327,
    VaccinationAppointmentID: 120,
    VaccinationVaccineID: 7,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Covid-19',
    VaccinationVaccineCost: '10.00',
  },
  {
    VaccinationID: 328,
    VaccinationAppointmentID: 120,
    VaccinationVaccineID: 2,
    VaccinationOutcomeID: 1,
    VaccinationVaccineName: 'Typhoid',
    VaccinationVaccineCost: '35.00',
  },
];
